In [33]:
import os
import pathlib
import pathlib as P
from pathlib import Path
import json
import pickle
import collections as clt
from collections import defaultdict

In [2]:
import pandas as pd

In [8]:
THIS_FILE = Path("__file__").resolve()
ROOT = THIS_FILE.parent.parent.parent

In [9]:
ROOT

PosixPath('/home/dataset-local/data_local/shaojiangyi/latence-project')

In [12]:
sw_path = ROOT / "data" / "swissprot_2022_04.pkl"

In [13]:
sw_path.exists()

True

In [14]:
sw_df = pd.read_pickle(sw_path)

In [28]:
sw_df

,proteins,accessions,genes,sequences,annotations,string_ids,orgs,interpros,exp_annotations,prop_annotations,cafa_target
0,001R_FRG3G,Q6GZX4;,2947773,MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQV...,[GO:0046782|IEA],[],654924,[IPR007031],[],[],False
1,002L_FRG3G,Q6GZX3;,2947774,MSIIGATRLQNDKSDTYSAGPCYAGGCSAFTPRGTCGKDWDLGEQT...,"[GO:0033644|IEA, GO:0016021|IEA]",[],654924,[IPR004251],[],[],False
2,002R_IIV3,Q197F8;,4156251,MASNTVSAQGGSNRPVRDFSNIQDVAQFLLFDPIWNEQPGSIVPWK...,[],[],345201,[],[],[],False
3,003L_IIV3,Q197F7;,4156252,MYQAINPCPQSWYGSPQLEREIVCKMSGAPHYPNYYPVHPNALGGA...,[],[],345201,[],[],[],False
4,003R_FRG3G,Q6GZX2;,2947775,MARPLLGKTSSVRRRLESLSACSIFFFLRKFCQKMASLVFLNSPVY...,[],[],654924,[],[],[],False
...,...,...,...,...,...,...,...,...,...,...,...
568358,Z_SABVB,Q6UY62;,3077249,MGNSKSKSKLSANQYEQQTVNSTKQVAILKRQAEPSLYGRHNCRCC...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],2169992,"[IPR024183, IPR038485, IPR003224]",[],[],False
568359,Z_SHEEP,P08105;,,MSSSLEITSFYSFIWTPHIGPLLFGIGLWFSMFKEPSHFCPCQHPH...,[],[],9940,[],[],[],False
568360,Z_TACVF,Q88470;,956594,MGNCNRTQKPSSSSNNLEKPPQAAEFRRTAEPSLYGRYNCKCCWFA...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],928313,"[IPR024183, IPR038485, IPR003224]",[],[],False
568361,Z_TAMVU,A9JR22;,6301276,MGLRYSKEVRDRHGDKDPEGRIPITQTMPQTLYGRYNCKSCWFANK...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],45223,"[IPR024183, IPR038485, IPR003224]",[],[],False
568362,Z_WWAVU,B2ZDY1;,,MGLRYSKDVKDRYGDREPEGRIPITLNMPQSLYGRYNCKSCWFANK...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],46919,"[IPR024183, IPR038485, IPR003224]",[],[],False

In [15]:
tsv_path = pathlib.Path("sprot_2204_a3m_counts.tsv").absolute()

In [16]:
msa_countdf = pd.read_csv(tsv_path, sep="\t")

In [17]:
msa_countdf

,path,counts (queryl),counts
0,/home/dataset-assist-0/datafile/shaojiangyi/la...,109,108
1,/home/dataset-assist-0/datafile/shaojiangyi/la...,1033,1032
2,/home/dataset-assist-0/datafile/shaojiangyi/la...,2012,2011
3,/home/dataset-assist-0/datafile/shaojiangyi/la...,1360,1359
4,/home/dataset-assist-0/datafile/shaojiangyi/la...,3,2
...,...,...,...
489217,/home/dataset-assist-0/datafile/shaojiangyi/la...,2023,2022
489218,/home/dataset-assist-0/datafile/shaojiangyi/la...,165,164
489219,/home/dataset-assist-0/datafile/shaojiangyi/la...,3319,3318
489220,/home/dataset-assist-0/datafile/shaojiangyi/la...,1800,1799
489221,/home/dataset-assist-0/datafile/shaojiangyi/la...,2014,2013

In [20]:
msa_countdf["path"] = msa_countdf["path"].apply(lambda x: os.path.basename(x).removesuffix(".a3m"))

In [21]:
msa_countdf

               path  counts (queryl)  counts
0       C4S1A_XENLA              109     108
1        CCR5_RHIBE             1033    1032
2        ATPB_CLOP1             2012    2011
3        BETB_BRUSU             1360    1359
4         BM2_INBYA                3       2
...             ...              ...     ...
489217  ZN169_HUMAN             2023    2022
489218  TPRA1_CAEBR              165     164
489219  ZN180_HUMAN             3319    3318
489220  ZN181_BOVIN             1800    1799
489221  ZN181_HUMAN             2014    2013

[489222 rows x 3 columns]

In [22]:
s1 = set(msa_countdf["path"].tolist())

In [23]:
name_set = set(sw_df.loc[sw_df["prop_annotations"].apply(lambda x: x == []), "proteins"])

In [24]:
s1.issubset(name_set)

True

In [25]:
name_set.issubset(s1)

True

In [26]:
name_list = sw_df.loc[sw_df["prop_annotations"].apply(lambda x: x == []), "proteins"].tolist()

In [29]:
data_path = ROOT / "data" / "dataset_state_ind_dict.pkl"

In [31]:
with open(data_path, "rb") as h:
    data = pickle.load(h)

In [32]:
data.keys()

dict_keys(['train', 'test', 'ind_test'])

In [36]:
data["exp_train"] = defaultdict(dict)

In [37]:
TASKS = [
    "cellular_component",
    "molecular_function",
    "biological_process",
]

In [39]:
for t in TASKS:
    data["exp_train"][t] = {"proteins": name_list}

In [40]:
saving_path = ROOT / "data" / "dataset_with_exp_train.pkl"

In [42]:
with open(saving_path, "wb") as h:
    pickle.dump(data, h)