In [1]:
import pathlib
import pathlib as P
import functools as ft
import itertools as it
import collections as clt

In [2]:
import Bio.SeqIO as sio
import Bio.SeqIO.FastaIO as fsio
import Bio.Seq as sq
import Bio.SeqRecord as sr

In [3]:
import pandas as pd

In [4]:
swpath = pathlib.Path("/home/dataset-assist-0/datafile/shaojiangyi/latence-dataset/swissprot_2022_04.pkl")
swdf = pd.read_pickle(swpath)

In [5]:
no_anno_df = swdf.loc[swdf["prop_annotations"].apply(lambda x: x == [])]

In [6]:
no_anno_df

,proteins,accessions,genes,sequences,annotations,string_ids,orgs,interpros,exp_annotations,prop_annotations,cafa_target
0,001R_FRG3G,Q6GZX4;,2947773,MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQV...,[GO:0046782|IEA],[],654924,[IPR007031],[],[],False
1,002L_FRG3G,Q6GZX3;,2947774,MSIIGATRLQNDKSDTYSAGPCYAGGCSAFTPRGTCGKDWDLGEQT...,"[GO:0033644|IEA, GO:0016021|IEA]",[],654924,[IPR004251],[],[],False
2,002R_IIV3,Q197F8;,4156251,MASNTVSAQGGSNRPVRDFSNIQDVAQFLLFDPIWNEQPGSIVPWK...,[],[],345201,[],[],[],False
3,003L_IIV3,Q197F7;,4156252,MYQAINPCPQSWYGSPQLEREIVCKMSGAPHYPNYYPVHPNALGGA...,[],[],345201,[],[],[],False
4,003R_FRG3G,Q6GZX2;,2947775,MARPLLGKTSSVRRRLESLSACSIFFFLRKFCQKMASLVFLNSPVY...,[],[],654924,[],[],[],False
...,...,...,...,...,...,...,...,...,...,...,...
568358,Z_SABVB,Q6UY62;,3077249,MGNSKSKSKLSANQYEQQTVNSTKQVAILKRQAEPSLYGRHNCRCC...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],2169992,"[IPR024183, IPR038485, IPR003224]",[],[],False
568359,Z_SHEEP,P08105;,,MSSSLEITSFYSFIWTPHIGPLLFGIGLWFSMFKEPSHFCPCQHPH...,[],[],9940,[],[],[],False
568360,Z_TACVF,Q88470;,956594,MGNCNRTQKPSSSSNNLEKPPQAAEFRRTAEPSLYGRYNCKCCWFA...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],928313,"[IPR024183, IPR038485, IPR003224]",[],[],False
568361,Z_TAMVU,A9JR22;,6301276,MGLRYSKEVRDRHGDKDPEGRIPITQTMPQTLYGRYNCKSCWFANK...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],45223,"[IPR024183, IPR038485, IPR003224]",[],[],False
568362,Z_WWAVU,B2ZDY1;,,MGLRYSKDVKDRYGDREPEGRIPITLNMPQSLYGRYNCKSCWFANK...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],46919,"[IPR024183, IPR038485, IPR003224]",[],[],False

In [10]:
seq_recs = (sr.SeqRecord(id=seq_name,name=seq_name,description="",seq=sq.Seq(seq_str)) for seq_name, seq_str in zip(no_anno_df["proteins"], no_anno_df["sequences"]))

In [11]:
saving_path = "/home/dataset-assist-0/datafile/shaojiangyi/latence-dataset/swissprot_2022_04_no_anno.fa"
with open(saving_path, "w") as h:
    writer = fsio.FastaWriter(h, wrap=10000000)
    writer.write_records(seq_recs)

In [14]:
no_anno_df.shape[0] * 2

978444

In [7]:
anno_df = swdf.loc[swdf["prop_annotations"].apply(lambda x: x != [])]

In [8]:
anno_df

,proteins,accessions,genes,sequences,annotations,string_ids,orgs,interpros,exp_annotations,prop_annotations,cafa_target
239,11K_PAVHV,P0DJZ0;,,MQNNTTGMDTKSLKNCGQPKAVCTHCKHSPPCPQPGCVTKRPPVPP...,"[GO:0030430|IDA, GO:0039526|IEA]",[],648237,[],[GO:0030430],"[GO:0033643, GO:0043656, GO:0043657, GO:001899...",False
240,11S1_CARIL,B5KVH4;,,MAKPILLSIYLCLIIVALFNGCLAQSGGRQQHKFGQCQLNRLDALE...,"[GO:0019863|IEA, GO:0045735|IC, GO:0048316|IEP...",[],32201,"[IPR022379, IPR006044, IPR006045, IPR014710, I...","[GO:0045735, GO:0048316, GO:0010431]","[GO:0048608, GO:0048316, GO:0007275, GO:002241...",False
242,11S1_MACIN,C0HLR7;,,LSTLNTHNLPLLRLVYLEREDLVAVHVDDLNNQANQLDQKLDGGLL...,"[GO:0019863|IDA, GO:0045735|IEA]",[],60698,[IPR011051],[GO:0019863],"[GO:0003674, GO:0019863, GO:0005488, GO:001986...",False
244,11S2_SESIN,Q9XHP0;,105163414,MVAFKFLLALSLSLLVSAAIAQTREPRLTQGQQCRFQRISGAQPSL...,"[GO:0042735|NAS, GO:0045735|NAS, GO:0010431|IEP]",[],4182,"[IPR022379, IPR006044, IPR006045, IPR014710, I...",[GO:0010431],"[GO:0048608, GO:0048316, GO:0007275, GO:002241...",False
258,128UP_DROME,P32234; Q9V648;,36288,MSTILEKISAIESEMARTQKNKATSAHLGLLKAKLAKLRRELISPK...,"[GO:0005737|IBA, GO:0005525|IDA, GO:0003924|IE...",[7227.FBpp0087084],7227,"[IPR012675, IPR045001, IPR031167, IPR006073, I...",[GO:0005525],"[GO:0032561, GO:0019001, GO:0036094, GO:004316...",True
...,...,...,...,...,...,...,...,...,...,...,...
568337,ZZEF1_MOUSE,Q5SSH7; Q499C8; Q6ZQC5; Q8C710; Q8CI54;,195018,MGNAPSNSSEDEAAAAGGEGWSPHQDWAADSGTTPGPGPAAAVLPS...,"[GO:0009986|IDA, GO:0098794|IDA, GO:0048786|ID...",[10090.ENSMUSP00000068790],10090,"[IPR004939, IPR011992, IPR002048, IPR008979, I...","[GO:0009986, GO:0098794, GO:0048786, GO:004520...","[GO:0050794, GO:0061659, GO:0023051, GO:007064...",True
568338,ZZZ3_HUMAN,Q8IYH5; B7WPC6; Q6N004; Q6N070; Q8IYP0; Q8IYR1...,26009,MAASRSTRVTRSTVGLNGLDESFCGRTLRNRSIAHPEEISSNSQVR...,"[GO:0140672|IDA, GO:0072686|IC, GO:0005730|IDA...",[9606.ENSP00000359837],9606,"[IPR009057, IPR017930, IPR001005, IPR000433, I...","[GO:0140672, GO:0072686, GO:0005730, GO:000565...","[GO:0050794, GO:0072686, GO:0034654, GO:000613...",True
568339,ZZZ3_MOUSE,Q6KAQ7; Q3TMK6; Q3V189;,108946,MVGTCHSMAASRSTRVTRSTVGLNGLDESFCGRTLRNRSIAHPEEI...,"[GO:0140672|IDA, GO:0072686|IC, GO:0005730|ISO...",[10090.ENSMUSP00000101706],10090,"[IPR009057, IPR017930, IPR001005, IPR000433, I...","[GO:0140672, GO:0072686, GO:0051726, GO:005130...","[GO:0050794, GO:0015630, GO:0007275, GO:190249...",True
568348,Z_LASSJ,O73557;,956586,MGNKQAKAPESKDSPRASLIPDATHLGPQFCKSCWFENKGLVECNN...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],11622,"[IPR024183, IPR038485, IPR003224]",[GO:0046761],"[GO:0019058, GO:0019076, GO:0016032, GO:001906...",False
568350,Z_LYCVA,P18541; Q49K85;,,MGQGKSREEKGTNSTNRAEILPDTTYLGPLSCKSCWQKFDSLVRCH...,"[GO:0044220|IEA, GO:0020002|IEA, GO:0016020|IE...",[],11624,"[IPR024183, IPR038485, IPR003224]",[GO:0046761],"[GO:0019058, GO:0019076, GO:0016032, GO:001906...",False

In [9]:
seq_recs = (sr.SeqRecord(id=seq_name,name=seq_name,description="",seq=sq.Seq(seq_str)) for seq_name, seq_str in zip(anno_df["proteins"], anno_df["sequences"]))

In [10]:
saving_path = "/home/dataset-assist-0/datafile/shaojiangyi/latence-dataset/swissprot_2022_04_anno.fa"
with open(saving_path, "w") as h:
    writer = fsio.FastaWriter(h, wrap=10000000)
    writer.write_records(seq_recs)

In [11]:
79141 * 2

158282